# Generated by Django 3.0 on 2023-11-10 05:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 10, 5, 56, 13, 180150, tzinfo=utc)),
        ),
    ]
