# Generated by Django 3.0 on 2023-11-10 07:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20231110_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 10, 7, 3, 43, 59508, tzinfo=utc)),
        ),
    ]
