# Generated by Django 4.2.4 on 2023-11-11 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_alter_assignment_created_at_alter_assignment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 16, 11, 13, 939738, tzinfo=datetime.timezone.utc)),
        ),
    ]
