# Generated by Django 4.2.4 on 2023-11-13 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_alter_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='active',
        ),
    ]
