# Generated by Django 4.2.6 on 2023-11-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='calendar',
        ),
    ]
